name = "platform"
main = "src/index.ts"
compatibility_date = "2026-08-18"
account_id = "d9c9f1882a0a73e0a592e4470b85e0b4"

[[kv_namespaces]]
binding = "PLATFORM_KV"
id = "01e18ff1f99149828f665bd84d6ca953"
